twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        mercure_publish_jwt: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdfX0.vNOW2hD02pSbjq3F4vQE8-XwM4VooGhRkZjprA6getg'
    form_themes: 
        - 'form/purecss_layout.html.twig'
        - 'form/rolltype.html.twig'
        - 'form/trait_type.html.twig'
        - 'form/random_type.html.twig'
        - 'form/avatar_type.html.twig'
        - 'form/autocomplete.html.twig'
        - 'form/ajaxcomplete.html.twig'
        - 'form/hashtag.html.twig'
        - 'form/wikitext.html.twig'
        - 'form/wikitree_type.html.twig'
        - 'form/submitwait_type.html.twig'
        - 'form/custom_field.html.twig'
        - 'form/multi_checkbox_type.html.twig'

when@test:
    twig:
        strict_variables: true
