twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: 
        - 'form/purecss_layout.html.twig'
        - 'form/rolltype.html.twig'
        - 'form/trait_type.html.twig'
        - 'form/random_int_type.html.twig'
    globals:
        popup_param: '%second_screen%'

when@test:
    twig:
        strict_variables: true
