twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: 
        - 'form/purecss_layout.html.twig'
        - 'form/rolltype.html.twig'
        - 'form/trait_type.html.twig'
        - 'form/random_type.html.twig'
        - 'form/cropper_type.html.twig'
        - 'form/autocomplete.html.twig'
        - 'form/ajaxcomplete.html.twig'
        - 'form/hashtag.html.twig'
        - 'form/wikitext.html.twig'
        - 'form/wikitree_type.html.twig'

when@test:
    twig:
        strict_variables: true
