twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: 
        - 'form/purecss_layout.html.twig'
        - 'form/rolltype.html.twig'

when@test:
    twig:
        strict_variables: true
