version: "3.9"
services:
    symfony:
        build: .
        image: symfony:dev
        ports:
            - "8000:8000"
            - "9000:9000"
        volumes:
            - .:/www
        depends_on:
            - "mongo"

    mongo:
        image: "bitnami/mongodb:4.4"
        volumes:
            - ./var/mongodb:/bitnami/mongodb
