version: "3.9"
services:
    symfony:
        build: .
        image: symfony:dev
        volumes:
            - .:/app
        depends_on:
            - "mongo"
        network_mode: host

    mongo:
        image: "bitnami/mongodb:6.0"
        volumes:
            - eclipse-mongo:/bitnami/mongodb
        network_mode: host

    bun:
        image: oven/bun
        volumes:
            - .:/home/bun/app
        network_mode: host
        working_dir: /home/bun/app
        command: bun run webfont
        
    goapi:
        image: golang:alpine3.20
        volumes:
            - ./golang:/app
        network_mode: host
        working_dir: /app
        command: go run httpd.go

volumes:
    eclipse-mongo:
