version: "3.9"

services:
    web:
        build: ./docker/web
        image: symfony:dev
        volumes:
            - .:/app
        depends_on:
            - "mongo"
        network_mode: host

    mongo:
        image: "bitnami/mongodb:6.0"
        volumes:
            - eclipse-mongo:/bitnami/mongodb
        network_mode: host

    iconfont:
        image: oven/bun
        volumes:
            - .:/home/bun/app
        network_mode: host
        working_dir: /home/bun/app
        command: bun run webfont
        
    algogo:
        image: golang:alpine3.20
        volumes:
            - ./docker/algogo:/app
        network_mode: host
        working_dir: /app
        command: go run algorithm.go 3333

    pdfgofast:
        build: ./docker/pdfgofast
        image: pdfgofast:server
        network_mode: host

volumes:
    eclipse-mongo:
