version: "3.9"
services:
    symfony:
        build: .
        image: symfony:dev
        volumes:
            - .:/app
        depends_on:
            - "mongo"
        network_mode: host

    mongo:
        image: "bitnami/mongodb:6.0"
        volumes:
            - eclipse-mongo:/bitnami/mongodb
        network_mode: host

volumes:
    eclipse-mongo: