version: "3.9"
services:
    symfony:
        build: .
        image: symfony:dev
        ports:
            - "8000:8000"
        volumes:
            - .:/www
        depends_on:
            - "mongo"

    mongo:
        image: "bitnami/mongodb:4.4"
        volumes:
            - ./var/mongodb:/bitnami/mongodb

    websocket:
        image: symfony:dev
        volumes:
            - .:/www
        depends_on:
            - "symfony"
        command: "bin/console p:d"

    connection:
        image: symfony:dev
        volumes:
            - .:/www
        depends_on:
            - "symfony"
        command: "bin/console a:l"