<?php

/*
 * Eclipse Wiki
 */

namespace App\Service\StableDiffusion;

/**
 * Info a picture generated by Stable Diffusion
 */
class PictureInfo
{

    public function __construct(
            public string $full,
            public string $thumb,
            public string $width,
            public string $name,
            public string $prompt = '')
    {
        
    }

    static public function extractCleanKeywords(string $subject): array
    {
        $filtered = preg_replace('#[^a-z\s]#', ' ', strtolower($subject));

        return preg_split("/[\s]+/", $filtered, 0, PREG_SPLIT_NO_EMPTY);
    }

    public function getKeywords(): array
    {
        return static::extractCleanKeywords($this->prompt);
    }

}
