<?php

/*
 * Eclipse Wiki
 */

namespace App\Service\StableDiffusion;

/**
 * Info a picture generated by Stable Diffusion
 */
class PictureInfo
{

    public function __construct(
            public string $full,
            public string $thumb,
            public string $width,
            public string $name,
            public string $prompt = '')
    {
        
    }

}
