#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login_check:
    path: /login_check

app_tracker_show:
    path: /tracker/show
    controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    methods: GET
    defaults:
        template:  'tracker/show.html.twig'

        
# Landing page
app_dashboard:
    path: /
    controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    methods: GET
    defaults:
        template:  'dashboard.html.twig'        
        
# Help page for Wikitext language
help_wikitext:
    path: /helpwiki
    controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    methods: GET
    defaults:
        template:  'helpwiki.html.twig'

# Help page for this web application
help_application:
    path: /help
    controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    methods: GET
    defaults:
        template:  'help.html.twig'