#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login_check:
    path: /login_check

app_tracker_show:
    path: /tracker/show
    controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    methods: GET
    defaults:
        template:  'tracker/show.html.twig'
        
app_labo:
    path: /labo
    controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    methods: GET
    defaults:
        template:  'labo.html.twig'
