# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    generator:
        - [chinese, chinese]
        - [english, chinese]
        - [japanese, japanese]
        - [random, chinese]
        - [chinese, random]
        - [random, random]
    second_screen:
        max_size: 800
        delta_x: 0
        delta_y: 42
        name: 'PopupVNC'
        name_suffix: ' - Mozilla Firefox'
        config: 'width=400,height=400,directories=0,titlebar=0,toolbar=0,location=0,status=0,menubar=0,scrollbars=no,resizable=no'
        
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # MongoDB
    MongoDB\Driver\Manager:
        arguments:
            - '%env(resolve:DATABASE_URL)%'
            
    Trismegiste\Toolbox\MongoDb\RepositoryFactory:
        $dbName: '%env(resolve:DATABASE_NAME)%'
      
    app.mwpage.repository:
        class: Trismegiste\Toolbox\MongoDb\Repository
        factory: ['@Trismegiste\Toolbox\MongoDb\RepositoryFactory', 'create']
        arguments: ['mwpage']
    Trismegiste\Toolbox\MongoDb\Repository $pageRepo: '@app.mwpage.repository'
                     
    App\Repository\VertexRepository:
        arguments:
            $dbName: '%env(resolve:DATABASE_NAME)%'
            $collectionName: 'vertex'
            
    App\Repository\BluetoothMsgRepository:
        arguments:
            $dbName: '%env(resolve:DATABASE_NAME)%'
            $collectionName: 'bluetooth'            
    
    # WIKI
    App\Service\MediaWiki:
        arguments:
            $host: '%env(resolve:WIKISOURCE)%'

    App\Service\LocalInterwiki:
        arguments:
            $host: '%env(resolve:WIKISOURCE)%'            
                        
    App\Twig\MediaWikiExtension:
        arguments:
            $src: '%env(resolve:WIKISOURCE)%'
            
    Mike42\Wikitext\WikitextParser:
        arguments:
            - '@App\Twig\LinkRender'
            
    # PDF
    app.wikiparser.pdf:
        class: Mike42\Wikitext\WikitextParser
        arguments:
            - '@App\Twig\PdfLinkRender'
            
    App\Twig\PdfWikiParserExtension:
        arguments:
            $wikiParser: '@app.wikiparser.pdf'

    # Open AI
    App\Service\OpenAi:
        arguments:
            $secret: '%env(resolve:OPENAI_SECRETKEY)%'
            $engine: 'davinci'
            
   # FLAT FILE SECTION
    app.choicetype.repository:
        class: App\Repository\YamlRepository
        arguments: 
            $path: '%kernel.project_dir%/database/choicetype.yml'
            
    # Picture
    App\Service\AvatarMaker:
        arguments:
            $socNetFolder: '%kernel.project_dir%/public/socnet'

    # Custom Types
    App\Form\Type\FullTextChoice:
        arguments:
            $repo: '@app.choicetype.repository'
            
    App\Service\ObjectPushFactory:
        arguments:
            $mac: '%env(resolve:BLUETOOTH_MAC)%'
            $chan: '%env(resolve:BLUETOOTH_CHANNEL)%'
            
    # Console command
    App\Command\SecondScreenDaemon:
        arguments:
            - '%second_screen%'
            
    # Storage
    App\Service\Storage:
        arguments:
            $projectDir: '%kernel.project_dir%'
            $env: '%kernel.environment%'
            
    App\Repository\MapRepository:
        arguments:
            $template: '%twig.default_path%/map/config'
            