<?php

/*
 * eclipse-wiki
 */

namespace App\Form;

use App\Entity\Vertex;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\DataMapperInterface;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Traversable;

/**
 * Append a output generated by a LLM to a content of a vertex
 */
class LlmOutputAppend extends AbstractType implements DataMapperInterface
{

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
                ->add('generation', TextareaType::class, ['attr' => ['x-model' => 'content', 'rows' => 30]])
                ->add('save', SubmitType::class)
                ->setMethod('PATCH')
                ->setDataMapper($this)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefault('data_class', Vertex::class);
    }

    public function mapDataToForms(mixed $viewData, Traversable $forms): void
    {
        
    }

    public function mapFormsToData(Traversable $forms, &$viewData): void
    {
        
    }

}
